export const loginTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT"
};

export const healthRequestTypes = {
    REQUEST_YOUR_HEALTH_REQUESTS: "REQUEST_YOUR_HEALTH_REQUESTS",
    RECEIVE_YOUR_HEALTH_REQUESTS: "RECEIVE_YOUR_HEALTH_REQUESTS"
}